# Generated by Django 5.0 on 2023-12-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_branch_alter_college_code_alter_course_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='College Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(verbose_name='Course Duration'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=2, max_length=2, primary_key=True, serialize=False, verbose_name='Scheme Id'),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='State Code'),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhar_id',
            field=models.CharField(max_length=12, verbose_name='Aadhar ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='UID'),
        ),
    ]
